name: PyPi Release Workflow
on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Update version in setup.py
      run: |
        export VERSION="${GITHUB_REF#refs/tags/v}"
        echo "Version to set: ${VERSION}"
        sed -i "s/0.0.1/${VERSION}/g" setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e.
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py bdist_wheel sdist
        twine upload dist/*